# Generated by Django 6.0 on 2025-12-14 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellnessCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField()),
                ('security_notes', models.TextField(blank=True, null=True)),
                ('maintenance_notes', models.TextField(blank=True, null=True)),
                ('needs_maintenance', models.BooleanField(default=False)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellness_checks', to='users.employee')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellness_checks', to='booking.room')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('room', 'inspection_date'), name='unique_room_inspection_per_day')],
            },
        ),
    ]
