# Generated by Django 6.0 on 2025-12-14 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'نشطة'), ('ended', 'منتهية'), ('cancelled', 'ملغاة')], default='active', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'غير مدفوعة'), ('partial', 'مدفوعة جزئياً'), ('paid', 'مدفوعة')], default='unpaid', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('cash', 'نقدي'), ('card', 'بطاقة'), ('online', 'دفع إلكتروني')], default='cash', max_length=20)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('paid', 'مدفوع')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'متاحة'), ('occupied', 'مشغولة'), ('maintenance', 'صيانة')], default='available', max_length=20)),
                ('number', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('triple', 'Triple')], default='double', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
