# Generated by Django 6.0 on 2025-12-14 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'فعالة'), ('inactive', 'غير فعالة'), ('maintenance', 'تحت الصيانة')], default='active', max_length=20)),
                ('installation_date', models.DateField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='booking.room')),
            ],
        ),
        migrations.CreateModel(
            name='CameraRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('file_path', models.FileField(upload_to='camera_records/')),
                ('size', models.IntegerField(help_text='Size in MB')),
                ('description', models.TextField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='camera_records/videos/')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='monitoring.camera')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
