# Generated by Django 6.0 on 2025-12-14 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        ('booking', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee'),
        ),
        migrations.AddField(
            model_name='qr',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr', to='booking.booking'),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='qr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access.qr'),
        ),
    ]
